"""phase3_intensity_ewma_status

Revision ID: 2b930a0f60bf
Revises: 893377fc43a7
Create Date: 2026-06-09 11:36:50.193509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b930a0f60bf'
down_revision: Union[str, None] = '893377fc43a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('intensity', postgresql.ENUM('moderate', 'vigorous', name='intensity_type_enum'), nullable=True))
    op.add_column('daily_summaries', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('daily_summaries', sa.Column('acute_workload', sa.Float(), nullable=True))
    op.add_column('daily_summaries', sa.Column('chronic_workload', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_summaries', 'chronic_workload')
    op.drop_column('daily_summaries', 'acute_workload')
    op.drop_column('daily_summaries', 'status')
    op.drop_column('activity_logs', 'intensity')
    # ### end Alembic commands ###